#originally part of jupytor ipython notebook file
# Improved version of read counts
#The read counts were generated by the following linux command:
#for example, under the folder with 282R fastq.gz do the following
##for f in *.fastq.gz; do grep "^@" -c <(zcat $f); done >282R_stats_reads.txt 



import csv
def count_reads(input_fname, output_fname):
    
    #read files for raw counts
    with open (input_fname) as f:
        raw_counts=[]
        for line in f:
            raw_counts.append(int(line))
        print ("Finished loading raw counts!")

    f.close()
    
    
    #take whichever is smaller in R1 or R2 as total # of reads for each sample (cell)
    reads=[]
    for i in range(0,len(raw_counts)):
        if (i%2==1):
            reads.append(min(raw_counts[i-1], raw_counts[i]))

    print "The total number of sampels are %d"%len(reads)
    
    #Write the result to a new file
    with open (output_fname, 'a') as outf:
        spamwriter = csv.writer(outf, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
        for i in range(0, len(reads)):
            spamwriter.writerow([reads[i]])
    outf.close()
    print ('Finished writing to the file!')

#Calling the function
count_reads("281R_stats_reads.txt","281R_total_reads.csv")